<?php

/**
 * @file
 *
 * Ensure EXIF data from original image exists in derivitive images
 *
 * basically we duplicate the image_gd image toolkit (or rather reuse the
 * toolkit's functions) but in the save we copy exif data over before we finish.
 */

/**
 * Implements hook_libraries_info().
 */
function image_exif_libraries_info() {
  $libraries = array();

  $libraries['pjmt'] = array(
    'name'              => 'PHP JPEG Metadata Toolkit',
    'vendor url'        => 'http://www.ozhiker.com/electronics/pjmt/',
    'download url'      => 'http://www.ozhiker.com/electronics/pjmt/download.html',
    'version arguments' => array(
      'file'      => 'Toolkit_Version.php', // Could be any file with version info
      'pattern'   => '/\$GLOBALS\[\'Toolkit_Version\'\] = "(.*)";/',
      'lines'     => 100,
    ),
    'files'             => array(
      'php'     => array(
        'EXIF.php',
      ),
    )
  );
  return $libraries;
}

/**
 * Implements hook_image_toolkits().
 */
function image_exif_image_toolkits() {
  module_load_include('toolkit.inc', 'image_exif');
  $result = libraries_detect('pjmt');
  
  if (!$result || $result['error']) {
    if (user_access('administer site configuration')) {
      drupal_set_message(t('EXIF Metadata Retention cannot be used; the PHP JPEG Metadata Toolkit cannot be found.'), 'error', FALSE);
    }
    watchdog('image_exif', 'EXIF Metadata Retention cannot be used; the PHP JPEG Metadata Toolkit cannot be found.', array(), WATCHDOG_ERROR);

    $available = FALSE;
  }
  else {
    $available = TRUE;
  }

  return array(
    'exif' => array(
      'title'     => t('EXIF Metadata Retention'),
      'available' => $available,
    ),
  );
}

